### ISSUE TITLE
CURIEs

### ISSUE THREAD

**Issue by randallsquared** [inadarei/hyper#1]
Given HAL's example, let's be careful about CURIE usage. 

## which type

We should follow the suggestion of https://www.w3.org/TR/2010/NOTE-curie-20101216/#sec_2.2. in specifying that fields contain either IRIs or CURIEs, or else limiting CURIEs to SafeCURIEs where the value might also be an IRI.  This removes ambiguity, since unsafe CURIEs can  have the same character sequence as IRIs.

## where

CURIEs are at least useful for `rels`, but where else may they be used?  At least some examples show CURIE usage in `uri`.   However, it seems like there's an opportunity to make things simpler if we treat the `h` namespace as a CURIE and specify it as a default CURIE always available:

```json
{"prefix": "h", "href": "http://hyperjson.io/names/"} 
```

If we then specify that the names (object keys) should never be treated as IRIs, then we can dispense with the SafeCURIE requirement for those.   Or not; requiring that no key in the `body` is semantically an IRI seems like a fairly large restriction to impose on users!

Combining those (except all SafeCURIEs), we'd have a minimal example of

```json
{
  "head": {
    "curies": [{"prefix": "ex", "href": "http://api.example.com/"}],
    "links": [{"uri": "[ex:employees]", "rels": ["self"]}]
  },
  "body": {
    "department": "North-East",
    "employees": {
      "label": "Department Employees",
      "[h:value]": {
        "cca78b82-59d5-49d3-bbfe-779de5248dbd": {
          "firstname": "Brianne",
          "lastname": "Watsica",
          "job-title": "Senior Infrastructure Administrator",
          "[h:links]": [
            {
              "uri": "[ex:employees/cca78b82-59d5-49d3-bbfe-779de5248dbd]",
              "rels": ["[ex:employee]"]
            }
          ]
        },
        "5e552416-f143-4bee-9a07-0e6fa8e96c12": {
          "firstname": "Jose",
          "lastname": "Jakubowski",
          "title": "Regional Sales Representative",
          "[h:links]": [
            {
              "uri": "[ex:employees/5e552416-f143-4bee-9a07-0e6fa8e96c12]",
              "rels": ["[ex:employee]"]
            }
          ]
        }
      }
    },
    "budget": "500M USD"
  }
}

```

**Comment by randallsquared** [comment]
Actually, it looks like keys (in the HAL to Hyper Example) are already intended to allow CURIEs.   So, if that's the case, then just specifying the `h` namespace as a CURIE is an immediate and simplifying win.

**Comment by inadarei** [comment]
Yes, I like both of your suggestions very much. Will update accordingly. Thank you!

**Comment by inadarei** [comment]
Actually, on a second thought: 

1. While safeCuries are more safe, they are also very awkward to use and more importantly: things like `{'[ex:whatever]': {...}}` will be error-prone to produce in many languages, at least by hand.

Final conclusion, after discussing it with Randall:  we will clarify in the documentation that  if something is a legal CURIE, and if there is a defined prefix, it's a CURIE, and not a URI, and if someone defines a `data` prefix, they're basically stopping "data:" URIs from being properly parsed in the same document. In which case they may want to reconsider the prefix.
