### ISSUE TITLE
how to declare and use CURIE prefixes

### ISSUE THREAD

**Issue by dret** [inadarei/hyper#15]
i am a little confused how exactly CURIE prefixes are declared and applied. it's essentially the same problem HAL faces (and so far doesn't clearly specify). how are conflicting declarations handled? what about multiple declarations on "parallel levels" (but those seem to be discouraged/disallowed)? why doesn't it clearly say "there MUST NOT be more than one `h:head` at the top level, and there MUST NOT be any `h:head` at lower levels"?

**Comment by inadarei** [comment]
But it does? 

> "There SHOULD be only one h:head property at the top level. All subsequent h:head properties after the first one, or the ones at deeper levels MUST be ignored."

http://hyperjson.io/props/head

**Comment by dret** [comment]
that's a SHOULD. that's different from a MUST NOT.

> SHOULD:   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

i you use SHOULD, people may ignore it, and things still shouldn't break. i think in this case things break, as it makes it impossible to resolve CURIEs in a well-defined way.

if you choose SHOULD, i think you have to specify how to handle conflicting `h:head` information. that probably would become rather tricky. so i'd make that a MUST NOT.
